from typing import Protocol

class MarketDataProtocol(Protocol):
    async def run(self) -> None: ...

class OrderBookDataProtocol(Protocol):
    async def run(self) -> None: ...

class OrderBookAnalyzerProtocol(Protocol):
    async def run(self) -> None: ...

class IndicatorEngineProtocol(Protocol):
    async def run(self) -> None: ...

class StrategyProtocol(Protocol):
    async def run(self) -> None: ...

class RiskManagerProtocol(Protocol):
    async def run(self) -> None: ...

class TraderProtocol(Protocol):
    async def run(self) -> None: ...